from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep

driver=webdriver.Chrome()
driver.get("https://www.wikipedia.org/")
driver.maximize_window()
sleep(3)
search_box=driver.find_element(By.ID,"searchInput")
print(search_box)
english_lang=driver.find_element(By.ID,"js-link-box-en")
print(english_lang)
logo=driver.find_element(By.CSS_SELECTOR,".central-featured-logo")
print(logo)
languages=driver.find_elements(By.CSS_SELECTOR,".central-featured-lang")
print(languages)
print("Total languages in central block:",len(languages))
driver.back()
sleep(2)
driver.forward()
sleep(2)
driver.refresh()
sleep(2)
print("Final Page Title:",driver.title)
driver.quit()